---
- name: Network Automation on R1
  hosts: ios
  gather_facts: false
  connection: local

  tasks:

    - name: Configure VLAN on R1
      ios_config:
        lines:
          - description VLAN subinterface
          - encapsulation dot1q 20 native
          - ip address 192.168.20.1 255.255.255.0
        parents: interface f0/1.20

    - name: Configure OSPF on R1
      ios_config:
        lines:
          - router-id 1.1.1.1
          - network 192.168.1.10 0.0.0.255 area 0
        parents: router ospf 1

    - name: Backup Config | Show Current Running Configuration
      ios_command:
        commands:
          - show running-config  
      register: config
 
    - name: Backup Config | Save Running Configuration to ./backup/
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "backup/show_run_{{ inventory_hostname }}.txt"